### ISSUE TITLE
Clairvoyant doesn't see special roles

### ISSUE THREAD

**Issue by NotDaniel59** [Alf21/ttt2-role_cv#7]
v0.9.2b

issue:
Clairvoyant is not able to see special roles anymore in the scoreboard, this happens 100% of the time

Collection:
https://steamcommunity.com/workshop/filedetails/?id=2466441155

**Comment by TimGoll** [comment]
Fixed in dev of gamemode base: https://github.com/TTT-2/TTT2/pull/857
